# Generated by Django 3.1.6 on 2023-09-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('buffet', models.BooleanField(default=False, null=True)),
                ('card_khan', models.BooleanField(default=False, null=True)),
                ('ticket_print', models.BooleanField(default=False, null=True)),
                ('accessible', models.BooleanField(default=False, null=True)),
                ('libary', models.BooleanField(default=False, null=True)),
                ('resturant', models.BooleanField(default=False, null=True)),
                ('coffe_shop', models.BooleanField(default=False, null=True)),
                ('ATM', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=800)),
                ('phone', models.CharField(max_length=15)),
                ('carwash', models.BooleanField(blank=True, default=False, null=True)),
                ('movie', models.ManyToManyField(related_name='m_cinema', to='home.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='DayAndDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=30)),
                ('date_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(max_length=50)),
                ('ticket_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c_times', to='cinema.cinema')),
                ('day_and_date', models.ManyToManyField(related_name='dd_schedule', to='cinema.DayAndDate')),
                ('movie', models.ManyToManyField(related_name='m_times', to='home.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='play_time',
            field=models.ManyToManyField(related_name='pt_cinemas', to='cinema.PlayTime'),
        ),
    ]
