# Generated by Django 3.1.6 on 2023-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='movie',
            field=models.ManyToManyField(related_name='m_play_time', to='home.Movie'),
        ),
    ]
