# Generated by Django 3.1.6 on 2023-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_playtime_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(upload_to='cinema_images'),
        ),
    ]
