# Generated by Django 3.1.6 on 2023-09-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_cinemarating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemarating',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_ratings', to='cinema.cinema'),
        ),
    ]
