# Generated by Django 3.1.6 on 2023-09-26 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0009_delete_commentdislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemacomment',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_cinemacomments', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='cinemacomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_cinemacomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_dislikes', to='cinema.cinemacomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_cc_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
