# Generated by Django 3.1.6 on 2023-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230925_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='coming_soon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
