# Generated by Django 3.1.6 on 2023-09-26 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_movie_coming_soon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentdislike',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
    ]
