# Generated by Django 3.1.6 on 2023-09-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='play_time',
            new_name='cartitem_play_time',
        ),
    ]
