# Generated by Django 3.1.6 on 2023-09-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20230923_2013'),
        ('cart', '0003_auto_20230923_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
