# Generated by Django 3.1.6 on 2023-09-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20230924_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartitem_play_time',
            new_name='cartitem_playtime',
        ),
    ]
