# Generated by Django 3.1.6 on 2023-09-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230924_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartitem_playtime',
            new_name='playtime',
        ),
    ]
